export const TYPING_DEBOUNCE_MS = 300
export const TYPING_SEND_MIN_INTERVAL_MS = 3000
export const TYPING_IDLE_STOP_MS = 5000
export const SEARCH_DEBOUNCE_MS = 400
export const READ_MARK_DEBOUNCE_MS = 500
export const TYPING_INDICATOR_CLEAR_MS = 8000
